### PR TITLE
sonatype nexus - quirks modes

### LINKED ISSUE #753: Credentials for npm repositories have no effect
**What happened**:
Credentials for npm are configured as documented in .ocmconfig or command line:
```
type: generic.config.ocm.software/v1
configurations:
  - type: credentials.config.ocm.software
    consumers:
      - identity:
          type: Registry.npmjs.com
          hostname: common.repositories.cloud.sap
        credentials:
          - type: Credentials
            properties:
              username: gardener-lm-ocm
              password: ...
```

**What you expected to happen**:
Access to private npm registries is possible. But results in 401 http error

**How to reproduce it (as minimally and precisely as possible)**:
any resource with type: npmPackage and located in any private npm registry

**Anything else we need to know**:
The type ` type: Registry.npmjs.com`differs in syntax from all other types (OCIRegisrty, HelmChartRepository) and why a capital R?

**Environment**:

### PR DESCRIPTION
**Pull request by hilmarf**
## Description

Two step token auth doesn't work with Nexus and the REST endpoint for a dedicated version doesn't exist. With this PR, Read-Access is done only via Basic-Auth and in case the specified version endpoint is not found, it will now try to load the complete package description from one level above. That should contain ALL existing versions, incl. the requested one.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🎇 Restructuring
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

- Fixes #753 and #769

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
- [ ] Separate ticket for tests # (issue/pr)

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: pkg/iotools/digests_test.go [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+	"github.com/open-component-model/ocm/pkg/iotools"
+)
+
+var _ = Describe("digests.go tests", func() {
+	It("DecodeBase64ToHex", func() {
+		hx, err := iotools.DecodeBase64ToHex("04cXMnFlKzgudf//lH/VqGUtFkplvGv0BCmPREEJsVYTJrxyiBFlsOiZIrjPENBkHWPnK6kOG53VTiqtsILNgw==")
+		Expect(err).To(BeNil())
+		Expect(hx).To(Equal("d387173271652b382e75ffff947fd5a8652d164a65bc6bf404298f444109b1561326bc72881165b0e89922b8cf10d0641d63e72ba90e1b9dd54e2aadb082cd83"))
+
+		hx, err = iotools.DecodeBase64ToHex("sha512-04cXMnFlKzgudf//lH/VqGUtFkplvGv0BCmPREEJsVYTJrxyiBFlsOiZIrjPENBkHWPnK6kOG53VTiqtsILNgw==")
```
Comment (Skarlso) [inline pkg/iotools/digests_test.go:20]: Why is there a sha prefix? :D It's not a sha. 🤔

File: pkg/contexts/ocm/accessmethods/npm/method.go [hunk 2]
```diff
@@ -96,43 +96,69 @@ func (a *AccessSpec) GetInexpensiveContentVersionIdentity(access accspeccpi.Comp
...
+		var project npm.Project
+		err = json.Unmarshal(buf.Bytes(), &project)
+		if err != nil {
+			return nil, errors.Wrapf(err, "cannot unmarshal version metadata for %s", a.PackageVersionUrl())
+		}
+		v, ok := project.Version[a.Version]
+		if !ok {
+			return nil, errors.Newf("version '%s' doesn't exist", a.Version)
+		}
+		version = v
```
[the remark this answers is not in the document]
Comment (hilmarf) [reply pkg/contexts/ocm/accessmethods/npm/method.go]: it's an ugly workaround - I know
but again yell at the ones, that don't plan to implement proper REST API, to be compliant with others

reason https://github.com/open-component-model/ocm/issues/769 because of https://github.com/sonatype/nexus-public/issues/224

added some comments

File: pkg/contexts/credentials/repositories/npm/config_test.go [hunk 3]
```diff
@@ -26,8 +26,8 @@ var _ = Describe("Config deserialization Test Environment", func() {
 		spec := npm.NewRepositorySpec("testdata/.npmrc")
 
 		_ = Must(ctx.RepositoryForSpec(spec))
-		id := identity.GetConsumerId("registry.npmjs.org", "pkg")
-
+		id, err := identity.GetConsumerId("registry.npmjs.org", "pkg")
+		Expect(err).To(BeNil())
```
Comment (mandelsoft) [inline pkg/contexts/credentials/repositories/npm/config_test.go:30]: you could use `Must` here, similar to the line below

File: pkg/contexts/ocm/accessmethods/npm/method.go [hunk 4]
```diff
@@ -96,43 +96,70 @@ func (a *AccessSpec) GetInexpensiveContentVersionIdentity(access accspeccpi.Comp
...
-// PackageUrl returns the URL of the NPM package (Registry/Package/Version).
+// PackageUrl returns the URL of the NPM package (Registry/Package).
 func (a *AccessSpec) PackageUrl() string {
+	return a.Registry + path.Join("/", a.Package)
+}
+
+// PackageVersionUrl returns the URL of the NPM package-version (Registry/Package/Version).
+func (a *AccessSpec) PackageVersionUrl() string {
 	return a.Registry + path.Join("/", a.Package, a.Version)
 }
```
Comment (mandelsoft) [inline pkg/contexts/ocm/accessmethods/npm/method.go:107]: If a.Registry ends with a / the resulting URL will probably not work. We had this problem when testing the maven part.

File: pkg/contexts/ocm/accessmethods/npm/method.go [hunk 5]
```diff
@@ -170,12 +188,34 @@ func reader(a *AccessSpec, fs vfs.FileSystem, ctx cpi.ContextProvider, tar ...st
...
+		return nil, err
+	}
 	c := &http.Client{}
 	resp, err := c.Do(req)
 	if err != nil {
 		return nil, err
 	}
+	if resp.StatusCode == http.StatusNotFound {
+		// maybe it's stupid Nexus - https://github.com/sonatype/nexus-public/issues/224?
+		defer resp.Body.Close()
```
[the remark this answers is not in the document]
Comment (Skarlso) [reply pkg/contexts/ocm/accessmethods/npm/method.go]: OH so sorry, I just realised that this is passing along the body. Okay, in that case, just copy the body into another reader and pass that along instead. Alternatively, change the signature to just give back bytes.

[the remark this answers is not in the document]
Comment (Skarlso) [reply pkg/contexts/ocm/accessmethods/npm/method.go]: And don't worry about multiple closes. Response body can be closed multiple times without a problem.

File: pkg/contexts/credentials/repositories/npm/config_test.go (hunk 3 above)
Comment (hilmarf) [reply pkg/contexts/credentials/repositories/npm/config_test.go]: done

File: pkg/contexts/ocm/accessmethods/npm/method.go (hunk 4 above)
Comment (hilmarf) [reply pkg/contexts/ocm/accessmethods/npm/method.go]: done

File: pkg/contexts/ocm/accessmethods/npm/method.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (hilmarf) [reply pkg/contexts/ocm/accessmethods/npm/method.go]: done, please re-check

File: pkg/contexts/ocm/accessmethods/npm/method.go [hunk 6]
```diff
@@ -96,43 +96,70 @@ func (a *AccessSpec) GetInexpensiveContentVersionIdentity(access accspeccpi.Comp
 	return ""
 }
 
-// PackageUrl returns the URL of the NPM package (Registry/Package/Version).
+// PackageUrl returns the URL of the NPM package (Registry/Package).
 func (a *AccessSpec) PackageUrl() string {
-	return a.Registry + path.Join("/", a.Package, a.Version)
+	return a.Registry[:8] + path.Clean(path.Join(a.Registry[8:], a.Package))
```
Comment (mandelsoft) [inline pkg/contexts/ocm/accessmethods/npm/method.go:101]: I don't know whether :8 (https://) is  a good idea. May be just check whether the Registry has a / as suffix and adding a leading suffix if this is not the case, only.

File: pkg/contexts/ocm/accessmethods/npm/method.go (hunk 4 above)
Comment (mandelsoft) [reply pkg/contexts/ocm/accessmethods/npm/method.go]: I don't know whether :8 (https://) is a good idea. May be just check whether the Registry has a / as suffix and adding a leading suffix if this is not the case, only.

Package and version may not contain a /, anyway.

Comment (mandelsoft) [reply pkg/contexts/ocm/accessmethods/npm/method.go]: looks fine

**Review by mandelsoft — APPROVED** [review]
