### PR TITLE
fix: enable linter: maintidx

### LINKED ISSUE #91: enable linter: maintidx
> maintidx measures the maintainability index of each function.

Default is 20, which is too low I think, but we have some extreme functions, for example:
```
name: push, Cyclomatic Complexity: 35
name: apply, Cyclomatic Complexity: 51
```

### PR DESCRIPTION
**Pull request by yitsushi**
Issues fixed:
- Fix issues with auto fix (`--fix`).
- Rename `this` receivers.
- Fix language issues, most of the duplicated words like "the the".
- Removed unnecessary type conversion.
- Reduced complexity of the `_apply` function by extracting some parts into a separate function.
- Reduced complexity of the `push` function by extracting some parts into a separate function.

References:
- https://github.com/open-component-model/ocm/issues/91

Closes #91

### CODE REVIEW

**Comment by yitsushi** [comment]
Please review the extracted functions carefully, I tried to be careful, but it does not mean I did not miss something. These functions have no tests, so I couldn't verify everything with tests.
```
❯ go test ./pkg/docker/...
?       github.com/open-component-model/ocm/pkg/docker  [no test files]
?       github.com/open-component-model/ocm/pkg/docker/resolve  [no test files]
```

File: pkg/docker/pusher.go [hunk 1]
```diff
@@ -140,102 +140,15 @@ func (p dockerPusher) push(ctx context.Context, desc ocispec.Descriptor, src res
 		req = p.request(host, http.MethodPut, putPath...)
 		req.header.Add("Content-Type", desc.MediaType)
 	} else {
-		// Start upload request
```
Comment (mandelsoft) [inline pkg/docker/pusher.go:143]: I completely understand, why you restructured this code. The change looks ok.
But this code has been copied from  `github.com/containerd/containerd remotes/docker` (see README) to fix the retry behavior.
I would like to keep it as close as possible to the original to make it easier to handle changes in the original version.

File: cmds/ocm/commands/ocmcmds/common/resources.go [hunk 2]
```diff
@@ -443,12 +446,12 @@ func (o *ResourceAdderCommand) ProcessResourceDescriptions(listkey string, h Res
 	defer obj.Close()
 
 	for _, r := range resources {
-		ictx := ictx.Section("adding %s...", r.Spec().Info())
+		isctx := ictx.Section("adding %s...", r.Spec().Info())
```
Comment (mandelsoft) [inline cmds/ocm/commands/ocmcmds/common/resources.go:449]: The idea here was, to always have an input context (`ictx`) available, using the same name, regardless of the nesting level.

Therefore at the beginning of a nesting level a new local variable with the same name is created.
This makes the code look the same regardless of the level.

Is this renaming really required by the new linter?

File: cmds/ocm/topics/toi/bootstrapping/topic.go [hunk 3]
```diff
@@ -332,7 +332,7 @@ execution and reading provided executor outputs after the execution.
 /
 └── toi
     ├── inputs
-    │   ├── config      config info from package specification
+    │   ├── config      info from package specification
```
Comment (mandelsoft) [inline cmds/ocm/topics/toi/bootstrapping/topic.go:335]: I would omit `info` instead of `config`: the file `config` contains the configuration from the package specification.

May be, replace it by `configuration from package specification`to avoid the repetition of `config`.

File: pkg/contexts/oci/ociutils/helm/ignore/doc.go [hunk 4]
```diff
@@ -28,7 +28,7 @@ The formatting rules are as follows:
 
 Example:
 
-	# Match any file named foo.txt
+	# Match exact file name
```
Comment (mandelsoft) [inline pkg/contexts/oci/ociutils/helm/ignore/doc.go:31]: This is generated text by helm.

It means, that any occurrence of a file named `foo.txt` is matched, in contrast to /foo.txt, which would match the exact file. I think, this is what this comment want to describe.

File: pkg/contexts/ocm/accessmethods/localfsblob/method.go [hunk 5]
```diff
@@ -11,8 +11,10 @@ import (
 )
 
 // Type is the access type of a blob in a local filesystem.
-const Type = "localFilesystemBlob"
-const TypeV1 = Type + "/v1"
+const (
+	Type   = "localFilesystemBlob"
+	TypeV1 = Type + "/v1"
```
Comment (mandelsoft) [inline pkg/contexts/ocm/accessmethods/localfsblob/method.go:16]: If we change it anyway, could you use `TypeV1 = Type + runtime.VersionSeparator + "v1"` similar to the other occurrences.

**Review by mandelsoft — CHANGES_REQUESTED** [review]
Thanks, for all those typo fixes. This was for sure no fun. Just some minor things...

File: cmds/ocm/commands/ocmcmds/common/resources.go (hunk 2 above)
Comment (yitsushi) [reply cmds/ocm/commands/ocmcmds/common/resources.go:449]: Yes, and it can be misleading as well, not just for linters, but in general. Shadowing a variable can be tricky and annoying, because as a reader (or someone who wants to change something), they would expect it to be exactly the same, but it's not, it's a new input context with a new section (based on the previous input context).

File: cmds/ocm/topics/toi/bootstrapping/topic.go (hunk 3 above)
Comment (yitsushi) [reply cmds/ocm/topics/toi/bootstrapping/topic.go:335]:
```suggestion
    │   ├── config      configuration from package specification
```

File: pkg/contexts/oci/ociutils/helm/ignore/doc.go (hunk 4 above)
Comment (yitsushi) [reply pkg/contexts/oci/ociutils/helm/ignore/doc.go:31]: I would argue with that, if we go down the meaning of the words, `/foo.txt` is an exact path, while `foo.txt` is an exact filename.

But, I'll revert that change.

File: pkg/contexts/ocm/accessmethods/localfsblob/method.go (hunk 5 above)
Comment (yitsushi) [reply pkg/contexts/ocm/accessmethods/localfsblob/method.go:16]: that was an auto-fixed change with `--fix`. In general if we have more than one `const` or `var` lines, convention to group them together with `const (...)` and `var (...)`, that's why the linter auto-fixed it.

File: pkg/docker/pusher.go (hunk 1 above)
Comment (yitsushi) [reply pkg/docker/pusher.go:143]: I see.

This comment, at the top of the file, told me it's "original content":
```
// SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Open Component Model contributors.
//
// SPDX-License-Identifier: Apache-2.0
```

I'll revert the changes and add this directory to the ignore list (with a comment why ignored).

Comment (yitsushi) [reply pkg/docker/pusher.go]: done.

Actions taken:
- reverted all changed under `pkg/docker`
- disabled all checks for `pkg/docker`

File: cmds/ocm/topics/toi/bootstrapping/topic.go (hunk 3 above)
Comment (yitsushi) [reply cmds/ocm/topics/toi/bootstrapping/topic.go]: done.

Actions taken:
- applied suggested changes

File: pkg/contexts/ocm/accessmethods/localfsblob/method.go (hunk 5 above)
Comment (yitsushi) [reply pkg/contexts/ocm/accessmethods/localfsblob/method.go]: done.

Actions taken:
- applied suggested changes

File: cmds/ocm/commands/ocmcmds/common/resources.go (hunk 2 above)
Comment (mandelsoft) [reply cmds/ocm/commands/ocmcmds/common/resources.go:449]: I could also argument exactly the other way round. If I use the input context is several blocks, I always want to use the input context applicable for this block. If I always have to use another variable, depending on the block, the code is in, then this would be very error prone.

But I agree, that in most cases you are right. But as always, it depends on the intended use case.

**Review by mandelsoft — APPROVED** [review]
