### PR TITLE
move identity packages into tech packages

### LINKED ISSUE #820: Race condition in MatchingResolver
**What happened**:

There seems to be a race condition in the MatchingResolver. Usually, the parallel access to the member `rules` is synchronized (e.g. [here](https://github.com/open-component-model/ocm/blob/14692575ffd968ed5811de728b17411c8070d4b4/pkg/contexts/ocm/internal/resolver.go#L153)) but this is violated [here](https://github.com/open-component-model/ocm/blob/14692575ffd968ed5811de728b17411c8070d4b4/pkg/contexts/ocm/internal/context.go#L322). 

During our tests we got the following error:

```

WARNING: DATA RACE
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:580)
Write at 0x00c00044f248 by goroutine 86:
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:581)
  github.com/open-component-model/ocm/pkg/contexts/ocm/internal.(*MatchingResolver).AddRule()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:582)
      [/go/pkg/mod/github.com/open-component-model/ocm@v0.10.0/pkg/contexts/ocm/internal/resolver.go:165](mailto:/go/pkg/mod/github.com/open-component-model/ocm@v0.10.0/pkg/contexts/ocm/internal/resolver.go:165) +0x38b
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:583)
  github.com/open-component-model/ocm/pkg/contexts/ocm/internal.(*_context).AddResolverRule()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:584)
      [/go/pkg/mod/github.com/open-component-model/ocm@v0.10.0/pkg/contexts/ocm/internal/context.go:329](mailto:/go/pkg/mod/github.com/open-component-model/ocm@v0.10.0/pkg/contexts/ocm/internal/context.go:329) +0xea
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:585)
  github.com/open-component-model/ocm/pkg/contexts/ocm/internal.(*gcWrapper).AddResolverRule()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:586)
      <autogenerated>:1 +0x1f
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:587)
  github.com/gardener/landscaper/pkg/components/ocmlib.(*RegistryAccess).GetComponentVersion()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:588)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/ocmlib/registryaccess.go:144 +0x6b0
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:589)
  github.com/gardener/landscaper/pkg/components/model.GetComponentVersionWithOverwriter()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:590)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/model/registryaccess.go:31 +0x101
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:591)
  github.com/gardener/landscaper/pkg/components/ocmlib.(*ComponentVersion).GetReferencedComponentVersion()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:592)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/ocmlib/componentversion.go:77 +0x1f0
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:593)
  github.com/gardener/landscaper/pkg/components/model.fetchComponentVersion()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:594)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/model/componentversion_refs.go:226 +0x1f3
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:595)
  github.com/gardener/landscaper/pkg/components/model.getTransitiveComponentReferencesRecursively.gowrap2()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:596)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/model/componentversion_refs.go:203 +0x124
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:597)
 
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:598)
Previous read at 0x00c00044f248 by goroutine 87:
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:599)
  github.com/open-component-model/ocm/pkg/contexts/ocm/internal.(*_context).GetResolver()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:600)
      [/go/pkg/mod/github.com/open-component-model/ocm@v0.10.0/pkg/contexts/ocm/internal/context.go:322](mailto:/go/pkg/mod/github.com/open-component-model/ocm@v0.10.0/pkg/contexts/ocm/internal/context.go:322) +0xc6
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:601)
  github.com/open-component-model/ocm/pkg/contexts/ocm/internal.(*gcWrapper).GetResolver()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:602)
      <autogenerated>:1 +0x24
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:603)
  github.com/gardener/landscaper/pkg/components/ocmlib.(*RegistryAccess).GetComponentVersion()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:604)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/ocmlib/registryaccess.go:145 +0x6d5
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:605)
  github.com/gardener/landscaper/pkg/components/model.GetComponentVersionWithOverwriter()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:606)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/model/registryaccess.go:31 +0x101
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:607)
  github.com/gardener/landscaper/pkg/components/ocmlib.(*ComponentVersion).GetReferencedComponentVersion()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:608)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/ocmlib/componentversion.go:77 +0x1f0
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:609)
  github.com/gardener/landscaper/pkg/components/model.fetchComponentVersion()
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:610)
      /tmp/build/86a4261d/pull-request-gardener.landscaper-master-pr/pkg/components/model/componentversion_refs.go:226 +0x1f3
[04:35:15](https://concourse.ci.gardener.cloud/builds/306331845#L665a4bc5:611)
  github.com/gardener/landscaper/pkg/components/model.getTransitiveComponentReferencesRecursively.gowrap2()
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by mandelsoft**
#### What this PR does / why we need it

* Identity packages are specific packages related to the identity and credentials representation for dedicated technology, like OCI, HELP, NPM, ....

  So far, they are below the`builtin` package in the credential context area. But now, we have a dedicated `tech` master package holding all abstractions required by the library for dedicated technologies. Therefore, this seems to be the natural place to locate the identity part, also.

* There are several fixes required for the `ComponentResolver`

* Package renaming with GoLand produces strange artifacts in the import list. It introduces `...2` package aliases, which are not required. THis PR removes those artifacts, again. There are much more such artifacts, than produced by the included package renames,

#### Which issue(s) this PR fixes
Fixes #820

### CODE REVIEW

File: api/oci/extensions/repositories/ocireg/repository.go [hunk 1]
```diff
@@ -13,12 +13,12 @@ import (
 	"github.com/mandelsoft/logging"
 
 	"ocm.software/ocm/api/credentials"
-	"ocm.software/ocm/api/credentials/builtin/oci/identity"
 	"ocm.software/ocm/api/datacontext/attrs/rootcertsattr"
 	"ocm.software/ocm/api/oci/artdesc"
 	"ocm.software/ocm/api/oci/cpi"
 	"ocm.software/ocm/api/tech/docker"
 	"ocm.software/ocm/api/tech/docker/resolve"
+	identity2 "ocm.software/ocm/api/tech/oci/identity"
```
Comment (fabianburth) [inline api/oci/extensions/repositories/ocireg/repository.go:21]: no alias needed here

File: api/oci/extensions/repositories/ocireg/type.go [hunk 2]
```diff
@@ -9,8 +9,8 @@ import (
 	"github.com/containerd/containerd/reference"
 
 	"ocm.software/ocm/api/credentials"
-	"ocm.software/ocm/api/credentials/builtin/oci/identity"
 	"ocm.software/ocm/api/oci/cpi"
+	identity2 "ocm.software/ocm/api/tech/oci/identity"
```
Comment (fabianburth) [inline api/oci/extensions/repositories/ocireg/type.go:13]: no alias needed here

File: api/ocm/resolvers/component.go [hunk 3]
```diff
@@ -0,0 +1,137 @@
+package resolvers
```
Comment (fabianburth) [inline api/ocm/resolvers/component.go:1]: shouldn't it be possible to define such a component resolver based on similar rules as the component version resolver through a configuration object, so it also can be configured through the command line and retrieved from the context?

**Comment by fabianburth** [comment]
since you touched the resolvers here, could you perhaps also resolve https://github.com/open-component-model/ocm/issues/820 ?

File: api/oci/extensions/repositories/ocireg/repository.go (hunk 1 above)
Comment (mandelsoft) [reply api/oci/extensions/repositories/ocireg/repository.go:21]: jow, this goland, whenever you rename a package, you sometime get such renamed package aliases.

Comment (mandelsoft) [reply api/oci/extensions/repositories/ocireg/repository.go:21]: changed

File: api/oci/extensions/repositories/ocireg/type.go (hunk 2 above)
Comment (mandelsoft) [reply api/oci/extensions/repositories/ocireg/type.go:13]: changred

File: api/ocm/resolvers/component.go (hunk 3 above)
Comment (mandelsoft) [reply api/ocm/resolvers/component.go:1]: The component resolver is a special case required for particular application code.
In the library the only ComponentResolver is the MatchingResolver configured for the OCM Context.
This one is used by some special ref handlers in the CLI (request from Christian).

But this resolver is already configurable by the config management.

The only other application, so far, requiring a component resolver is the service model, because we have to resolve version constraints, here. This requires a ListVersions which is only available for a component. Therefore, a ComponentVersionResolver cannot be used.

The CLI plugin for the ServiceModel would use the context resolver, here, which is already configurable.

**Comment by Skarlso** [comment]
I'm in the process of fixing the tests. I'll include that last commit into that PR. Please hang on for a sec..

**Review by fabianburth — APPROVED** [review]
